<a href="https://colab.research.google.com/github/Amsayed3100/CodeAlpha_MachineLearning_Task02/blob/main/Task_02_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 04: Desease Prediction from medical data

In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.svm import SVC

In [28]:
df=pd.read_csv('heart (1).csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [29]:
df.shape

(1025, 14)

In [30]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [31]:
#Train,Test Split
X = df.drop(columns=['target'])
y = df['target']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,)

In [32]:
#Scalling
scale=StandardScaler()
scaled_X_train =scale.fit_transform(X_train)
scaled_X_test =scale.transform(X_test)

In [55]:
#SVM
svm=SVC(random_state=42)
svm_model=svm.fit(scaled_X_train,y_train)
pred=svm_model.predict(X_test)
accuracy= accuracy_score(y_test,pred)


#Logistic regression
log_reg= LogisticRegression(random_state=42)
Log_reg_model=log_reg.fit(scaled_X_train,y_train)
pred2=Log_reg_model.predict(X_test)
accuracy2= accuracy_score(y_test,pred2)
print(f"Logistic regression Accuracy: {accuracy2*100}%")


#RandomForest
random=RandomForestClassifier(random_state=42)
random_model=random.fit(scaled_X_train,y_train)
pred3=random_model.predict(X_test)
accuracy3=accuracy_score(y_test,pred3)


#XGboost
xgb=XGBClassifier(random_state=42)
xgb_model=xgb.fit(scaled_X_train,y_train)
pred4=xgb_model.predict(X_test)
accuracy4=accuracy_score(y_test,pred4)



print(f"SVM Accuracy: {accuracy*100}%")
print(f"Logistic regression Accuracy: {accuracy2*100}%")
print(f"RandomForest Accuracy: {accuracy3*100}%")
print(f"XGboost Accuracy: {accuracy4*100}%")

print(classification_report(y_test, pred))
print(classification_report(y_test, pred2))
print(classification_report(y_test, pred3))
print(classification_report(y_test, pred4))

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

Logistic regression Accuracy: 50.73170731707317%
SVM Accuracy: 50.24390243902439%
Logistic regression Accuracy: 50.73170731707317%
RandomForest Accuracy: 70.73170731707317%
XGboost Accuracy: 69.26829268292683%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       102
           1       0.50      1.00      0.67       103

    accuracy                           0.50       205
   macro avg       0.25      0.50      0.33       205
weighted avg       0.25      0.50      0.34       205

              precision    recall  f1-score   support

           0       0.50      1.00      0.67       102
           1       1.00      0.02      0.04       103

    accuracy                           0.51       205
   macro avg       0.75      0.51      0.35       205
weighted avg       0.75      0.51      0.35       205

              precision    recall  f1-score   support

           0       0.65      0.88      0.75       102
           1       0.82      0.53      0.65       103

    accuracy                           0.71       205
   macro avg       0.74      0.71      0.70       205
weighted avg       0.74      0.71      0.70       205

              precision    recall  f1-score   support

           0       0.62      0.96      0.76       102
           1       0.92      0.43      0.58       103

    accuracy                           0.69       205
   macro avg       0.77      0.69      0.67       205
weighted avg       0.77      0.69      0.67       205

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))